### ISSUE TITLE
Hide 'client_secret' from basic auth on the revad logs

### ISSUE THREAD

**Issue by SamuAlfageme** [cs3org/reva#1145]
Prevent the user details from leaking in the logs while using basic auth. `username:password` combination results in:
```
2020-09-07T07:41:14Z DBG credentials obtained from credential strategy: 
  &{Type:basic ClientID:username ClientSecret:password} pkg=rhttp service=reva traceid=d287ba9aeb200dee348061f989fb9fd9

2020-09-07T07:41:14Z DBG AuthenticateRequest: 
  type:"basic" client_id:"username" client_secret:"password"  against localhost:9142 pkg=rhttp service=reva traceid=d287ba9aeb200dee348061f989fb9fd9
```

**Comment by SamuAlfageme** [comment]
@ishank011 is this one covered by https://github.com/cs3org/reva/pull/1142/commits/519cc1905b257d68a57e4e123cc2d665e6c9414f? If so, I guess we can link the PR to auto-close on merge.

**Comment by ishank011** [comment]
Yep. I'll update the PR description
