### ISSUE TITLE
Etag absent in MD response from eosgrpc

### ISSUE THREAD

**Issue by ishank011** [cs3org/reva#1185]
https://github.com/cs3org/reva/blob/84f2c0ebc2d6ef4f2f14b2096fedf131058e28a5/pkg/eosclientgrpc/eosclientgrpc.go#L1238

Even though we try to look for the etag in the xattrs present in the response from the MD call, it is never actually present, hence it fails the smashbox tests. cc @SamuAlfageme

**Comment by ffurano** [comment]
Fixed by https://github.com/cern-eos/grpc-proto/commit/0de0dd8772b7014d07a21024c6e18c6e22d89b04

**Comment by ffurano** [comment]
And committed the consequent fix into the related PR  #1154
