### ISSUE TITLE
New HTTP "metrics" service renders WebDAV invalid

### ISSUE THREAD

**Issue by Daniel-WWU-IT** [cs3org/reva#1243]
@redblom @ishank011 There is a pretty big problem with the new `metrics` HTTP service. It is currently returning an empty string as its prefixed (based on Ishank's comments), but this causes, at least for us, all WebDAV requests to be passed to this metrics service. This leads to failing of any WebDAV call, of course. Here's how I configured the new service:
```
[http.services.metrics]
metrics_data_driver_type = "dummy"
metrics_data_location = ""
metrics_record_interval = 5000
```
Removing this section makes everything work again as expected.

**Comment by ishank011** [comment]
Fix: https://github.com/cs3org/reva/pull/1239/files#diff-f4eb95d3bf3e519f0d56cd2d4ea22f3a
