### ISSUE TITLE
reva_version="(Unknown)" on latest revad builds

### ISSUE THREAD

**Issue by SamuAlfageme** [cs3org/reva#1406]
For some reason, the git output that used to fill these variables:

https://github.com/cs3org/reva/blob/4a9be347ac29706e429d47525815e638f9770f29/Makefile#L5-L8

... is empty:

```
[salfagem@lxplus765 ~]$ kubectl exec -ti iop-gateway-6fbcd98bb-cgv5k -- /go/bin/revad -version
version= commit= go_version=go1.13.15 build_date=2021-01-15T14:10:42+0000
```

... which contrast with the version string returned by the reva client (generated on the daily release pipeline):

```
reva version
version=2021_01_15T150629_47119beffae215190124e98e063f1734b9e75938 commit=47119beffae215190124e98e063f1734b9e75938 go_version=go1.13.15 build_date=2021-01-15
```

---

This issue makes the `reva_version` exposed via `revad_sys_info` metric to be "`(Unknown)`"

```
# HELP revad_sys_info A metric with a constant '1' value labeled by various system information elements
# TYPE revad_sys_info gauge
revad_sys_info{reva_build_date="2021-01-15T14:10:42+0000",reva_version="(Unknown)"} 1
```

**Comment by SamuAlfageme** [comment]
Therefore, some of these values are missing on the site information dashboard: 

![image](https://user-images.githubusercontent.com/2644445/105002551-c500e680-5a31-11eb-96ec-d44182ec67c6.png)

cc/ @Daniel-WWU-IT

**Comment by Daniel-WWU-IT** [comment]
Nothing I can do about this. I use the information that is somehow built into Reva during CI, but if that is empty, I output this "(Unknown)" instead. I guess during all these recent changes to the CI, something must have broken...
