### ISSUE TITLE
shares folder etag cache implementation

### ISSUE THREAD

**Issue by butonic** [cs3org/reva#1410]
@ishank011 in https://github.com/cs3org/reva/blob/fcd6626946977706f61a9a4d61247d658cbbb25e/internal/grpc/services/gateway/storageprovider.go#L971-L995
the cache is checked in https://github.com/cs3org/reva/blob/fcd6626946977706f61a9a4d61247d658cbbb25e/internal/grpc/services/gateway/storageprovider.go#L988
which happens after the shares folder has been stated in https://github.com/cs3org/reva/blob/master/internal/grpc/services/gateway/storageprovider.go#L971

Why stat the shares folder if the result is not necessary until after the cache was checked? AFAICT https://github.com/cs3org/reva/blob/fcd6626946977706f61a9a4d61247d658cbbb25e/internal/grpc/services/gateway/storageprovider.go#L971-L986 should go into the else branch, right?

I'm trying to understand the caching logic.

**Comment by butonic** [comment]
same for statSharesFolder: https://github.com/cs3org/reva/blob/master/internal/grpc/services/gateway/storageprovider.go#L1020-L1039

**Comment by butonic** [comment]
Ok I get that in statHome you can return early when there is no shared folder ...

**Comment by butonic** [comment]
In case ther is a Shared folder ... the gateway will always return the cached etag until the TTL has been reached. That breaks webdav atomicity expectations ... 

in statHome we already have the stat of the home root. if we compare the tree modification times (which would require caching it ... or comparing it againts the ttl ofg the cached entry we could invalidate the cache earlier and only delay etag changes causet by share changes.

**Comment by ishank011** [comment]
Sounds good. Will need to cache the last timestamp when the etag was calculated as well. Will make the change
