### ISSUE TITLE
Revamp public shares authentication model

### ISSUE THREAD

**Issue by ishank011** [cs3org/reva#1549]
## Why?
With the current workflow with which public shares are handled, we run the risk of exposing the resource owner's token to random users who access the shared link. Using only the token corresponding to the public shares, the `Authenticate` gateway method can be called, which will return the owner's token.

https://github.com/cs3org/reva/blob/3b7e1f0a50d6a5683f5ca18e4b6983608e6ab62d/internal/http/services/owncloud/ocdav/dav.go#L177-L183

## Anonymous users
I propose using anonymous users to grant share-specific access. When a public share is created, a temporary user is created and assigned the appropriate grant for the shared file.
- For a share corresponding to `#/s/RMxHPGhqbRySVOH`, we add an ACL `u:public_RMxHPGhqbRySVOH:rwx`.
- When this link is accessed, the `Authenticate` method of type `publicshares` returns this user if it's able to find the share corresponding to it.
- This user is set in the context, and the file systems correctly handle the requests as the ACLs are already set.

## Possible issues
- Users can misuse these anonymous users like they can in the current implementation. While they won't be able to access actual files as they would be protected by ACLs, the returned token can still be used to perform other operations (manipulating shares, accessing info about other users). This would have to be handled in the HTTP and GRPC auth interceptors with checks that these anonymous users should only be allowed access to the `/remote.php/dav/public-files/` endpoint and those exposed by the public storage provider service.
- For file systems which use local extended attributes, adding ACLs corresponding to non-existent users should be trivial. However, for EOS, this won't work as EOS expects the UID to actually exist when performing operations. Hence, it would have to be handled separately. While setting arbitrary ACLs does work, to actually access the resource, we'll need to impersonate the owner.
- For every public share created, we'll need to add an ACL. This does not seem to be too major an issue, as for one particular resource, we shouldn't expect more than ~10 links to be created. Especially when we have the janitor cleaning up expired links, we can remove the ACLs at the same time.

Please let me know your thoughts about this @labkode @butonic @refs @dragotin

**Comment by C0rby** [comment]
I agree the the public shares authentication model needs to be revamped.
Is there no other way than to create users for the share? I'm not too familiar with the authentication model yet.

**Comment by C0rby** [comment]
While I was implementing the [signed url public links](https://github.com/cs3org/cs3apis/issues/110) I got some insights and see some more problems now.

**Comment by C0rby** [comment]
> Users can misuse these anonymous users like they can in the current implementation. While they won't be able to access actual files as they would be protected by ACLs, [...] that these anonymous users should only be allowed access to the /remote.php/dav/public-files/ endpoint and those exposed by the public storage provider service.

But then they would be able to access the shared files, right? I mean wouldn't it be possible to set put this user into the request context and issue a `InitiateDowload` request or some other request for files in that share?

**Comment by C0rby** [comment]
Nevermind. With the share token and password it's of course possible to access the share files... :facepalm:

**Comment by labkode** [comment]
@C0rby for the brute-force attack a very simple solution is to add a delay on wrong password (like when you wrongly type your password when `sudo-ing`)

**Comment by ishank011** [comment]
> Take the signature and expiration from the requested URL

Isn't expiration also part of the hashed signature, as per this https://github.com/cs3org/cs3apis/issues/110? How do you retrieve that?

> With basic authentication we could just call GetPublicShareByToken and provide the share token and password.

Nope. You call `Authenticate` with the token and password, which provides you the creator's token, which is what I want to change.

> We would need to use GetPublicShare instead but currently this method requires an authenticated context.

Both `GetPublicShare` and `GetPublicShareByToken` require an authenticated context.

> But I guess this also depends on how we revamp the public share authentication model.

What I propose above won't solve this. That is just to prevent exposing the creator's token to random users and is not really related to how we want to design the signed URLs

> by adding the password hash to the response we are enabling attacker to do offline brute-forcing on the share password hash

I don't really see the problem here. Do you mean that if a user knows the password to a share, and if he accesses `GetPublicShareByToken`, he will get the hashed password, and so he can figure out the salt? Isn't that true for our whole jwt token design?

**Comment by ishank011** [comment]
A better way IMO, instead of having the public share service return the password would be to delegate the whole signing process to it. Add a method called `GetShareBySignature` which takes the 256 bit signature and returns the share. Although, this won't be the minimal approach which we want to adopt for CS3APIs @labkode

**Comment by ishank011** [comment]
Or better yet, make the password parameter in `GetPublicShareByToken` a oneof between password and signature.

**Comment by labkode** [comment]
@ishank011 if the logic is to just "sign" that can be added to the CS3APIS. If the logic is "craft a signature that allows fine-grained permissions to download this file" I think that doesn't fit there.

**Comment by labkode** [comment]
In the old Reva implementation (pre-CS3APIs) we had a dedicated module to craft tokens:
https://github.com/cernbox/revaold/blob/master/api/token_manager_jwt/token_manager_jwt.go

**Comment by ishank011** [comment]
@labkode if we follow this approach

> Or better yet, make the password parameter in GetPublicShareByToken a oneof between password and signature.

then we just need to add a signature field to the `PublicShare` message which would be returned to the webdav service which can expose it.

**Comment by C0rby** [comment]
> @C0rby for the brute-force attack a very simple solution is to add a delay on wrong password (like when you wrongly type your password when `sudo-ing`)

That doesn't work. If someone has the hash they can just calculate hashes and compare them with the share hash.

**Comment by C0rby** [comment]
> > Take the signature and expiration from the requested URL
> 
> Isn't expiration also part of the hashed signature, as per this [cs3org/cs3apis#110](https://github.com/cs3org/cs3apis/issues/110)? How do you retrieve that?

The expiration is included in the signing process. When someone is using the signed URL then the expiration needs to be included in the request in a query parameter.

> > by adding the password hash to the response we are enabling attacker to do offline brute-forcing on the share password hash
> 
> I don't really see the problem here. Do you mean that if a user knows the password to a share, and if he accesses `GetPublicShareByToken`, he will get the hashed password, and so he can figure out the salt? Isn't that true for our whole jwt token design?

No I mean currently the share can only be accessed by doing a `GetPublicShareByToken` request which includes the share token and password. If an attacker wants to bruteforce the password they have to repeatedly make that request.
To prevent bruteforcing the service could have some sort of cooldown/delay like @labkode above.

But if the attacker has the hash then the only limit to bruteforcing is the computational complexity of the hash and the computing power of the attacker.

**Comment by C0rby** [comment]
So based of your comments I propose these changes https://github.com/cs3org/cs3apis/pull/118

**Comment by refs** [comment]
👍 conceptually it makes sense. I'm not aware of the side effects compared to other approaches, such as using a dedicated "maintenance" user only for public shares.

On a performance note, I wonder how much of a toll for a system would be due to the overhead of looking for a given user (not getting into indices here 🙈). Wondering as well if such users have to be filtered out from the UI, but these are implementation details. The concept is clear to me.

My only remarks are:
- Lack of comparison (YMMV) with a production environment, i.e: there is an average of 2 public links per user, on a deployment with 100.000 users there would potentially be 200.000 extra users (these are totally made up numbers)
- Filter out public users from the UI (sounds trivial, but still to keep it in mind?)
- Reverse engineer-able: the username generation composed of `public_publicSharetoken` is guessable.

**Comment by ishank011** [comment]
@refs thanks a lot for the comments!

Sorry, I didn't mention this in the explanation. We won't actually be creating any users. These would just be used to generate the jwt token. So when the `publicshare.Authenticate` method be called, 

https://github.com/cs3org/reva/blob/e8a00d9b236877bcb9302070a967cc7632e8ca84/pkg/auth/manager/publicshares/publicshares.go#L121-L128
instead of returning the creator of the share, we'll return
```
&userpb.User{
  Id: &userpb.UserId{
    OpaqueId: public_RMxHPGhqbRySVOH,
  },
}
```

The middleware will generate a token for this user which will be used to allow access to the shared file. When dismantling the token, we'll check that it's a special public-shares-only user and make sure that it has access only to the `/remote.php/dav/public-files/` endpoint and those exposed by the public storage provider service.

> using a dedicated "maintenance" user only for public shares

This is also an option, but the ACLs on all the shared resources will have the same principal then. So an attacker might use the token to access all such files.

> Reverse engineer-able: the username generation composed of public_publicSharetoken is guessable.

True but the token won't be of much use as the middleware will block access for these special users. They'll only be able to access the file shared with them (which they can anyway since they have the token).

**Comment by refs** [comment]
Ace! thanks @ishank011 for taking the time to go through the point :) all clear

**Comment by ishank011** [comment]
This approach has been superseded by https://github.com/cs3org/reva/pull/1669
