### ISSUE TITLE
Application passwords 

### ISSUE THREAD

**Issue by labkode** [cs3org/reva#1714]
As a user I want to generate a unique authentication token to act on my behalf with limited scope.
This token can be used in 3rd party applications or in case primary user credentials cannot be submitted to other parties.
Having such token allows for device-level controls. An example of my mail provider:

![Screenshot 2021-05-19 at 08 47 07](https://user-images.githubusercontent.com/5175912/118768042-cd055180-b87e-11eb-8a4c-771e1ed3ce07.png)

To achieve this functionality we need two tasks:
1) Implement an Auth Provider that consumes these tokens and gives back an authentication token on behalf of the user that generated it
2) A new API for create these tokens

@gmgigi96 will work on 1) and @ishank011 on 2).

**Comment by ishank011** [comment]
@labkode @gmgigi96 token minting and dismantling is handled in the gateway itself, so we don't need to delegate this to the auth provider. We just need to check that a user is present in the context and generate the token, else return an error.

I've created a PR to CS3APIs https://github.com/cs3org/cs3apis/pull/127, will coordinate with @gmgigi96 on the changes in reva.

**Comment by ishank011** [comment]
To start with, we can have the following scopes for applications:
- resource ([resourceInfo](https://cs3org.github.io/cs3apis/#cs3.storage.provider.v1beta1.ResourceInfo); [role](https://cs3org.github.io/cs3apis/#cs3.auth.provider.v1beta1.Role)) (we can reuse the code in the current `publicshare` scope)
- share (share (user/public/OCM); role)

**Comment by labkode** [comment]
@ishank011 We still need the auth provider. We need a way to list these tokens and remove the from the user. We need an "app password" that will be converted to that token that is mint in the gateway. 

I've discussed it this morning with @gmgigi96, we can have another chat tomorow
