### ISSUE TITLE
Understand reva runtime

### ISSUE THREAD

**Issue by ishank011** [cs3org/reva#1720]
Understand how [reva runtime](https://github.com/cs3org/reva/tree/master/cmd/revad) works and what we'd need to change to enable the plugin integration

**Comment by jimil749** [comment]
Hi @ishank011! I just had a basic look at the runtime package and also had a look at some plugin frameworks. Is it fine to have discussions over them over here?

**Comment by ishank011** [comment]
@jimil749 yep, please go ahead

**Comment by jimil749** [comment]
These are just my initial thoughts, any suggestions would be highly valuable!
