### ISSUE TITLE
ocm-provider route should be public?

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/reva#1751]
Start revad with one of the ocmd example configs:
```sh
cd examples/ocmd/ && mkdir -p /var/tmp/reva
../../cmd/revad/revad -c ocmd-server-1.toml
```
And then:
```sh
curl http://localhost:19001/ocm/ocm-provider/
curl http://einstein:relativity@localhost:19001/ocm/ocm-provider/
```

You will see the `/ocm-provider/` route is only accessible to logged in users?
Is this by design or an oversight?

**Comment by michielbdejong** [comment]
@ishank011 do you know?

**Comment by ishank011** [comment]
Hi @michielbdejong that is indeed a bug. https://github.com/cs3org/reva/pull/1832 should fix it
