### ISSUE TITLE
endPoint field in ocm-provider json should be camelCase?

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/reva#1752]
On http://localhost:19001/ocm/ocm-provider/ I see:
```json
{
   "enabled": true,
   "apiVersion": "1.0-proposal1",
   "host": "localhost",
   "endpoint": "https://localhost/ocm",
   "provider": "cernbox",
   "resourceTypes": [
      {
         "name": "file",
         "shareTypes": [
            "user"
         ],
         "protocols": {
            "webdav": "/cernbox/ocm_webdav"
         }
      }
   ]
}
```
but my code is looking for `endPoint`, not `endpoint`.

[Question to self:] Is this part of OCM documented somewhere?

**Comment by michielbdejong** [comment]
Looking at https://github.com/cs3org/OCM-API/pull/37 it was suggested as camelCase, but apparently this didn't make it into https://github.com/cs3org/OCM-API/blob/develop/spec.yaml#L33.

**Comment by glpatcern** [comment]
This was fixed in one of the last PRs around OCM
