### ISSUE TITLE
Sort share entries alphabetically

### ISSUE THREAD

**Issue by labkode** [cs3org/reva#1763]
When showing the list of shares to the end-user the list of not sorted alphabetically.

Probably we need to sort on server side in the Grappa/REST user manager.

![Screenshot 2021-06-04 at 10 36 45](https://user-images.githubusercontent.com/5175912/120772602-c46c7680-c520-11eb-8d60-daf827a0fc95.png)

**Comment by ishank011** [comment]
We can do it in ocs, that'll take care of all the drivers

**Comment by labkode** [comment]
@ishank011 true, wouldn't then make sense to have on the GRPC layer so is used by OCS and direct clients?

**Comment by ishank011** [comment]
Yep, that'd be perfect
