### ISSUE TITLE
Remove hardcoded notifications capability

### ISSUE THREAD

**Issue by pascalwengerter** [cs3org/reva#1805]
Just found out that the [ownCloud web frontend](https://github.com/owncloud/web/) incorrectly checks for notifications since the notifications capability in Reva, for historical reasons and contrary to the behavior in other capability cases, returns an array with a `"disable"` string (https://github.com/cs3org/reva/blob/a8c61401b662d8e09175416c0556da8ef3ba8ed6/tests/oc-integration-tests/local/frontend.toml#L110). 

To make it consistent we shouldn't return anything here until Reva/oCIS is capable of handling notifications.

Glad to take care of this myself when the time comes but also don't want to cause a breaking change in the Semver for this minor nitpicky issue

**Comment by labkode** [comment]
Hi @pascalwengerter, what do you need? To omit the value or to set it to something else?

**Comment by pascalwengerter** [comment]
> Hi @pascalwengerter, what do you need? To omit the value or to set it to something else?

I'd vote in favor of omitting it since from my understanding that's how non-boolean values are being treated so far (?)

**Comment by labkode** [comment]
@pascalwengerter from the code looks like this capability is not a boolean.

```
   if h.c.Capabilities.Notifications == nil {
                h.c.Capabilities.Notifications = &data.CapabilitiesNotifications{}
        }
        if h.c.Capabilities.Notifications.Endpoints == nil {
                h.c.Capabilities.Notifications.Endpoints = []string{"list", "get", "delete"}
        }

```

**Comment by pascalwengerter** [comment]
> @pascalwengerter from the code looks like this capability is not a boolean.
> 
> ```
>    if h.c.Capabilities.Notifications == nil {
>                 h.c.Capabilities.Notifications = &data.CapabilitiesNotifications{}
>         }
>         if h.c.Capabilities.Notifications.Endpoints == nil {
>                 h.c.Capabilities.Notifications.Endpoints = []string{"list", "get", "delete"}
>         }
> ```
> 
> The default would be an empty array.

Fine with me, too. Checking for an array length feels way cleaner than doing `if capabilities.notifications.endpoints[0] != "disable"` (which even contains a grammatical error)

**Comment by labkode** [comment]
@pascalwengerter great, so we need the oc QA team to evaluate this tests that set is as "disabled"
