### ISSUE TITLE
Driver api versioning?

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/reva#1810]
I noticed the signature of `RestoreRecycleItem` changed because my Nextcloud storage driver stopped working when I rebased on master. After some digging I found [this change](https://github.com/cs3org/reva/blame/9740eed3f3b5deb3c1a4f1a19c4ac1606820dffc/pkg/storage/storage.go#L46) from 5 days ago.

I know we are still using [ad-hoc APIs](https://reva.link/docs/overview/#the-problem-we-try-to-solve) for the storage, so changes like this are expected to be frequent and that's fine.

But maybe we can document a versioned Reva storage driver API?

**Comment by labkode** [comment]
Hi @michielbdejong that was one big breaking change. 
We usually announce it the gitter channels and in the changelog.
We plan to version the CS3APIS very soon. I don't expect major breaking changes anytime soon.

**Comment by michielbdejong** [comment]
Cool! I'll keep an eye on https://gitter.im/cs3org/REVA and take extra care to test my build after each rebase on master. Thanks!
