### ISSUE TITLE
Use Drone instead of Travis

### ISSUE THREAD

**Issue by tboerger** [cs3org/reva#200]
I would like to suggest to switch to https://cloud.drone.io instead of Travis CI, with Drone we got a lot more flexibility while testing and building the project, we can use any Docker container within the pipelines, we get native agents for arm and arm64 for free which could be nice to build releases automatically. The cloud offering is free for any open source project.

At ownCloud we are already using Drone for a long time.

**Comment by labkode** [comment]
Hi @tboerger, I've been checking out Drone and indeed the flexibility is much more than in Travis.

Could you setup the CI using the Drone cloud to push images to the Docker registry? If you don't have permissions to access the cs3org/reva repo let me know.

Thanks!

**Comment by tboerger** [comment]
If you enable the repository on drone cloud I can do that after my vacation.

**Comment by labkode** [comment]
@tboerger repo enabled, missing now the .drone.yml file to configure the pipelines.

**Comment by tboerger** [comment]
:+1: I will provide a pr directly after my vacation, in the meantime it won't trigger a drone build because of the missing drone config.

**Comment by labkode** [comment]
@tboerger great! Enjoy your holidays
