### ISSUE TITLE
add pragmatic favorites implementation

### ISSUE THREAD

**Issue by butonic** [cs3org/reva#2036]
The web ui needs an efficient way to list all files that have been marked as favorite by a user. We already persist the faverite flag on a per user basis in the extended attributes when using the decomposedfs. But for querying we need an efficient lookup, similar to the share manager.

Searching by favorite is one case of searching by metadata. While the bigger picture is tracked in https://github.com/cs3org/reva/issues/41 and https://github.com/cs3org/cs3apis/issues/8 we propose an intermediate solution.

As discussed in person we propose to introduce a go interface and implementation that the ocdav api can use to implement listing of favorite files. The ocdav service can then persist the favorites using that api, optionally also set them on the storage using extended attributes and read them from the api.

When this is done we can either add a `favorites manager` to the CS3 api or directly work on https://github.com/cs3org/reva/issues/41

@labkode @ishank011

**Comment by butonic** [comment]
from [gitter](https://gitter.im/cs3org/REVA?at=6135d56b7cd57813a8ad5628):
> #2036: is what I had in mind, just replicate the model for sharing. We'll need to extend the CS3APIS to provide that functionality. I suggest you start with the "metadata manager" driver and interface
> We hook it in the ocdav later as a workaround and when the CS3APIS plus the GRPC service are ready we port the logic from ocdav to this service

**Comment by labkode** [comment]
Initial work done here: https://github.com/cs3org/reva/pull/2071

**Comment by kulmann** [comment]
For enabling favorites in web we need a boolean capability `capabilities.files.favorites`.
Needs to be defined here: https://github.com/owncloud/ocis/blob/bbcea23e85b705aafee17e0fbf05d67cc961b819/ocs/pkg/service/v0/data/capabilities.go#L79
And then added with value `true` here:
https://github.com/owncloud/ocis/blob/dbb6367e92effdfde258c1fb03a14cbb60126e47/storage/pkg/command/frontend.go#L57

**Comment by labkode** [comment]
@kulmann does that enables the sidebar "Favourites" only or also the start icon in the row rendering?

**Comment by kulmann** [comment]
Enables everything related to favorites:
- nav item in the left sidebar with dedicated favorites view
- favorites star in the right sidebar
- context menu (right click) action for toggling favorites
