### ISSUE TITLE
Stop build if build-only step fails

### ISSUE THREAD

**Issue by labkode** [cs3org/reva#2056]
To reduce resource consumption in the CI the running steps should be short-circuited if the build-only phase fails.
@wkloucek ?

It usually happens that we create a PR and then we need to provide the changelog. By having this we have a very quick feedback and we avoid keeping a CI job that will never make it to green.

**Comment by phil-davis** [comment]
@dpakach can you get someone to have a look?

**Comment by wkloucek** [comment]
Or just do it as a separate step and make all others depending on it. It takes only 7 seconds and has no dependencies.

Though one might work on a PR first and see if its green and add the change log before marking the PR as ready. This workflow would then definitely break.
