### ISSUE TITLE
What should GetQuota return?

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/reva#2069]
The [GetQuota](https://github.com/cs3org/reva/blob/5c0e31adade364e7bfb1242bf0dfecc28d43743a/pkg/storage/storage.go#L55) function on the storage provider API returns two `uint64` values.
Are those "maxBytes" and "maxFiles" like in https://github.com/cs3org/go-cs3apis/blob/970eec3/cs3/storage/provider/v1beta1/resources.pb.go#L1491-L1505 ?

Or "total" and "used" like in https://github.com/cs3org/reva/blob/5c0e31adade364e7bfb1242bf0dfecc28d43743a/internal/http/services/owncloud/ocs/handlers/cloud/users/users.go#L130-L131 ?

Is there any documentation for this?
Maybe this function should return something a bit more typed, or at least we could improve the documentation.

**Comment by michielbdejong** [comment]
Is this because GetQuota on the storage provider gives the current user's quota for all storage spaces, and the Quota included in the ListStorageSpacesResponse is only for that one storage space?

**Comment by butonic** [comment]
sadly, the ocs api does not differentiate between different storage spaces. it cannot take into account quota on an external storage or a federated share. for ocis we decided to report the quote from the users home space. with the spaces concept and the graph api we introduce it will be possible to get the quote of every storage space the user has access to.

**Comment by michielbdejong** [comment]
Thanks for clarifying that!
But I'm still wondering, what is the meaning of the two `uint64` numbers?

**Comment by phil-davis** [comment]
I will guess and someone can confirm if I am correct:
`getQuotaRes.TotalBytes` = the total amount of storage that you are allowed to use (for example a number like 10,000,000,000 about 10GB)
`getQuotaRes.UsedBytes` = the number of bytes that your files/folders use at the moment (for example a number like 7,000,000,000 about 7GB)

And anyone can calculate that the remaining available storage space "free space" is 3,000,000,000 about 3GB.

**Comment by michielbdejong** [comment]
Yes, that answer makes sense to me. That's probably what it is. I'll add a code comment!
