### ISSUE TITLE
Documentation for archiver

### ISSUE THREAD

**Issue by kulmann** [cs3org/reva#2096]
For implementing the download as archive in [ownCloud Web](https://github.com/owncloud/web/pull/5832) I'd like to see some basic documentation. Especially helpful: example requests for
- downloading folder `/test` from the user home of `einstein`
- downloading folder `/test` from the password protected public link `GFZpdiHgFOonejL` with password `asdf`

**Comment by kulmann** [comment]
cc @ishank011 @gmgigi96

**Comment by kulmann** [comment]
Since the API only accepts a dir and a list of file names, I'm especially unsure how to proceed with public links. I would have expected that the provided path is relative to the authenticated user's home directory. That doesn't seem to be the case.

**Comment by gmgigi96** [comment]
The archiver does not support yet a password protected public link download.
Instead, to download a normal file/folder, the `dir` parameter should have as prefix `/home`, so according to your example `dir=/home` and `file=test`.

**Comment by kulmann** [comment]
Just to get this straight, in your CERN-Box environment you'd have `/` as dir, so that we need to provide configuration for the path prefix, right?

**Comment by kulmann** [comment]
In order to get this going for public links as well I'm discussing with @wkloucek right now that this should be implemented using resource ids, not paths.

**Comment by kulmann** [comment]
Ideas for improvement tracked in https://github.com/cs3org/reva/issues/2097 - closing here.
