### ISSUE TITLE
Change archiver to work resource id based

### ISSUE THREAD

**Issue by kulmann** [cs3org/reva#2097]
As I've learned in https://github.com/cs3org/reva/issues/2096 the archiver service currently works with absolute paths. That brings at least two limitations:

1: we need configuration for the web ui for defining a path prefix. In the CERN-Box environment this is not needed (`/`), for any standard ownCloud environment it would be `/home`. This kind of knowledge should not be needed in the web UI (+ this will not work with our spaces implementation)
2: similar to (1) folder downloads will not work for public links

Switching to resource id based file/folder selection for the archive will resolve (1) and (2). Additionally it will allow us to have support folder downloads on password protected public links without extra effort after https://github.com/owncloud/ocis/pull/2536 is merged.

**Comment by kulmann** [comment]
cc'ing @wkloucek for more details if needed

**Comment by gmgigi96** [comment]
The current archiver implementation has the same interface of an old archiver service, we used, and yes, it is limited.
So, I will change the interface to support both paths and resources ids, providing to the archiver a list of `path` and/or a list of `id`.

**Comment by kulmann** [comment]
Awesome, thank you 🤩

**Comment by butonic** [comment]
Related: https://github.com/owncloud/ocis/issues/2521

Cc @kulmann I don't know if @jvillafanez looked into this as well.
