### ISSUE TITLE
Accept 201 as response from OCM create share

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/reva#2201]
[OCM specified](https://cs3org.github.io/OCM-API/docs.html#/paths/~1shares/post) `201 Created` as a response code for a share-create request.
But reva [only accepts](https://github.com/cs3org/reva/blob/v1.14.0/pkg/ocm/share/manager/json/json.go#L341)  `200 OK`

**Comment by glpatcern** [comment]
Fixed long ago
