### ISSUE TITLE
OCM notifications endpoint is not published

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/reva#2202]
The OCM spec [requires](https://cs3org.github.io/OCM-API/docs.html#/paths/~1notifications/post) a `/notifications` endpoint
but it's not listed as Unprotected in https://github.com/cs3org/reva/blob/v1.14.0/internal/http/services/ocmd/ocmd.go#L97

**Comment by glpatcern** [comment]
(Fixed some time ago)
