### ISSUE TITLE
edge: WOPI server may encounter two different fileids for same resource

### ISSUE THREAD

**Issue by butonic** [cs3org/reva#2635]
When a publicly shared file is edited by a logged in user and a guest user the fileid is different for a resoucre is different when accessing it via a public link. This causes problems with the WOPI extension where users may enter and leave an edit session. If the fileid changes writes may fail when the original editor leaves the session.

In any case the public storage provider MUST NOT replace the storage space id in the reference with a public storage space id.

The current approach of returning a `type:public` storage space when listing spaces is wrong. 

The correct approach is to only return a space for a resource when dealing with public link requests. That would also eliminate the `public` storage space in the listing of spaces a user has access to.

This will change the implementation significantly, basically it is a rewrite.

**Comment by wkloucek** [comment]
already fixed in https://github.com/cs3org/reva/pull/2646 :+1:
