### ISSUE TITLE
Fix static logging issues

### ISSUE THREAD

**Issue by ishank011** [cs3org/reva#2640]
Logging is always expected to be done via the static logger embedded in the context. However, in some places in the code, we use the native library loggers which are not associated with the context and thus are not handled properly in the reva runtime.

Eg, in https://github.com/cs3org/reva/blob/32b439e51b946d0d1089f5bcb21135fad59b0574/pkg/auth/manager/oidc/oidc.go#L126

the message should be logged via the logger obtained from calling `appctx.GetLogger(ctx)`. This needs to be fixed in all such instances.

**Comment by KarthikSundar2002** [comment]
I will start working on this issue

**Comment by ishank011** [comment]
Hi @KarthikSundar2002  thanks a lot for taking this up! Let me know if you have any questions or need any clarifications

**Comment by afzal442** [comment]
hey @ishank011, I would like to look into it. 🍀

**Comment by afzal442** [comment]
I think, this issue has been addressed. It needs to be closed.

cc @glpatcern

**Comment by glpatcern** [comment]
@afzal442 that particular example was indeed refactored, but there are others with the pattern mentioned by @ishank011
