### ISSUE TITLE
Building from source fails

### ISSUE THREAD

**Issue by nilsocket** [cs3org/reva#2675]
go version: `1.18`
`Linux nil 5.10.105-1-MANJARO #1 SMP PREEMPT Fri Mar 11 14:12:33 UTC 2022 x86_64 GNU/Linux`

on `make deps`
I get error: `go get doesn't work outside of a module for goimports`
With a temporary fix of using `go install x.com/goimports@latest`

Next,
on `make build`
I get error: `missing go.sum entry for golang.org/x/text/...`
with a temporary fix of running `go get` the above package names

Thank you.

**Comment by wkloucek** [comment]
I'm also on Manjaro, but still on `go version go1.17.8 linux/amd64`.

`go mod tidy` also fails for me.

Could you try to run `go run ./cmd/revad`? That's the actual reva server you want to run. It will report that you're missing a config.

You can choose a config from the [examples directory](https://github.com/cs3org/reva/tree/master/examples) by running `go run ./cmd/revad -dev-dir examples/xxx`

**Comment by KarthikSundar2002** [comment]
This issue arises due to the fact that the Makefile is outdated, I can make a PR with the correct Makefile

**Comment by pascalwengerter** [comment]
> This issue arises due to the fact that the Makefile is outdated, I can make a PR with the correct Makefile. After fixing the Makefile, things seem to work fine.

Feel free to open a PR, of course! :)

**Comment by KarthikSundar2002** [comment]
I have opened a PR https://github.com/cs3org/reva/pull/2747 with the changes.

**Comment by KarthikSundar2002** [comment]
Now that my PR is merged, I guess this issue can be closed after verifying

**Comment by ishank011** [comment]
Fixed by https://github.com/cs3org/reva/pull/2747
