### ISSUE TITLE
reva failed due to next cloud configuration.

### ISSUE THREAD

**Issue by shokri-navid** [cs3org/reva#2815]
I installed reva on my machine but when I run reva command inside `/cmd/revad` folder but I am getting this error: 

> http service dataprovider could not be started,: Please specify 'endpoint' in '[grpc.services.storageprovider.drivers.nextcloud]

but I have this `endpoint` property in my /etc/revad/revad.toml :
 
```
[grpc.services.storageprovider.drivers.nextcloud]
endpoint = "http://localhost:8002/index.php/apps/sciencemesh/"
user_layout = "{{.Username}}"
```

**Comment by michielbdejong** [comment]
Might be related to #2782 - I will dive into it next week!

**Comment by michielbdejong** [comment]
Testing this out with the image from https://github.com/cs3org/ocm-test-suite/tree/main/servers/revad
and then `docker run -it revad /bin/bash`
Inside the container:
```sh
cd /reva/
git pull
apt install -y golang
make deps
make build-revad
./cmd/revad/revad -c ./examples/nextcloud-integration/
```
I was able to replicate the error:
```
"http service dataprovider could not be started,: Please specify 'endpoint' in '[grpc.services.storageprovider.drivers.nextcloud]'"

**Comment by glpatcern** [comment]
Fixed / obsoleted
