### ISSUE TITLE
State of OCM in reva

### ISSUE THREAD

**Issue by ishank011** [cs3org/reva#2942]

**Comment by redblom** [comment]
Currently a second OCM share (from another user) overrides the OCM share from the first user when both shares use the same folder structure (name clash). The resulting mount paths will be the same.
This is relevant for data transfer type OCM shares as well.
Note that there is an unimplemented case in the [`UpdateReceivedOCMShare`](https://github.com/cs3org/reva/blob/1ace372c4ba058f8f549e9cad882eb56c8745ec0/internal/grpc/services/gateway/ocmshareprovider.go#L398) method that seems relevant here.

@ishank011  Is this something to be resolved/discussed with this here issue, or somewhere else?

**Comment by phil-davis** [comment]
Note: I think that this issue is related - https://github.com/owncloud/ocis/issues/3880 and not actually fixed/resolved.

There is "trouble" if 2 users create a file with the same name (and usually it will have different content). They both share the file with user3. user3 receives 2 incoming shares that have the same naming, and has trouble to distinguish them and to fetch/get the content of each.

**Comment by redblom** [comment]
Yes, seems definitely related. 
Based on the [current code](https://github.com/cs3org/reva/blob/1ace372c4ba058f8f549e9cad882eb56c8745ec0/internal/grpc/services/gateway/ocmshareprovider.go#L398) I can only guess what the original idea (if any) was on how to deal with this.

The actual precise mechanism of how to deal with name clashes needs to be defined first.

**Comment by ishank011** [comment]
@redblom @phil-davis we're planning on getting rid of the implementation that brings about this issue in the first place, as part of the GSoC project

**Comment by redblom** [comment]
Some requirements:

- `ocmshareprovider.UpdateReceivedOCMShare` should be implemented for all fields (`state`, `name` (mount_point basically is `share.Name`), etc)
- The name clash issue (overriding existing shares) should be prevented in the first place, when accepting the share, by creating a unique mount_point. Eg. based on a timestamp.
