### ISSUE TITLE
CERN: Project Spaces

### ISSUE THREAD

**Issue by labkode** [cs3org/reva#2964]
• A space is owned by a service account, quota is assigned to this service account.
• A space needs 5 roles: owners, administrators, writers, readers and viewers (only view, no download, no sync)
• Administrators/Owners are the only ones that can share from the project space
• Shares owner is the service account, initiator is either the owner or the administrator
• owners and administrators can see each other shares (means can see all shares belonging to service account)
• A project space has a dedicated trash-bin independent of the user's personal trash-bin.
• Anyone with write permissions should be able to see this trash-bin and restore accordingly
• Anyone with write permissions should be able to see versions and restore accordingly
• A lightweight/guest account (not CERN user) can access the project space on behalf of the service account
• A project space could have a presentation template (like a README.md file that is rendered at the top, like DropBox)
• Dedicated application to create project spaces with approval workflows for CERNBox admins
• Dedicated workflows for quota increases
•  Admins/Owners can share subtrees/files inside a Space with people who do not have a role in the space.
• The roles can contain either individual people or groups

**Comment by labkode** [comment]
@dragotin @micbar can you please go to each of the points described above and specify what is currently implemented?

**Comment by ishank011** [comment]
This is a blocker https://github.com/owncloud/web/issues/6972

**Comment by dragotin** [comment]
@ishank011 in owncloud/web#6972 is a question open from @kulmann Can you help pls?

**Comment by labkode** [comment]
> > A space is owned by a service account, quota is assigned to this service account.
> 
> This is implemented, but in a different way. The space belongs to no service account (has no owner) and the quota is stored as a space attribute
> 

I think this could be fine as we can hide the details in the backend implementation.
When creating a space, we'll create it in EOS and assign the quota and service account to the EOS project space.

> > A space needs 5 roles: owners, administrators, writers, readers and viewers (only view, no download, no sync)
> 
> We have 3 Roles: Managers (can add and remove users), Editors and Viewers. Users with the admin role can change the quota. "Can change space quota" is a permission of the user Role, not of the space.
> 
Managers look like our admins. If a manager has "Can change space quota" change it for multiple spaces or only to the one that  the user is a manager?



> > Administrators/Owners are the only ones that can share from the project space
> 
> That is different: Currently Viewers and Editors can share from a space but not increase the permissions

This won't work for us. We expect only administrators to be able to share for security reasons. 
The administrator of a project set the ACLs of the project, people will view permissions should not mangle the acls.

> 
> > Shares owner is the service account, initiator is either the owner or the administrator
> 
> Spaces have no owner and everything is transparent. All space members can see all shares.

Idem as first comment.
> 
> > owners and administrators can see each other shares (means can see all shares belonging to service account)
> 
> All space members see all shares. There is no service account needed. That is the key feature of spaces (no owner)

This won't work for us as explained above.
> 
> > A project space has a dedicated trash-bin independent of the user's personal trash-bin.
> 
> Implemented. Go to the 3 dots in the spaces menu to reach the trash-bin
> 
> > Anyone with write permissions should be able to see this trash-bin and restore accordingly
> 
> Implemented.
> 
> > Anyone with write permissions should be able to see versions and restore accordingly
> 
> Implemented
> 
> > A lightweight/guest account (not CERN user) can access the project space on behalf of the service account
> 
> oCIS does not work with lightweight accounts for the GA release. This is CERN specific. The master branch should again be merged into edge, so the code should be on the edge branch. I do not know if it works there and have no means to test that.

OC10 has this concept that is named Guest Accounts. When do you plan to introduce it?
> 
> > A project space could have a presentation template (like a README.md file that is rendered at the top, like DropBox)
> 
> Implemented.
> 
> > Dedicated application to create project spaces with approval workflows for CERNBox admins
> 
> This is CERN specific development. We have workflows on the Roadmap, but not scope of GA.
> 
> > Dedicated workflows for quota increases
> 
> Not part of GA like general workflows, but on the Roadmap.
> 
> ## Policies
> Regarding spaces and who can do which operation within a space we will implement space policies. We already experimented with the OpenPolicyAgent (https://www.openpolicyagent.org/) and this is on our Roadmap. This could help in all of these use cases and will replace our "File Access Firewall"
> 
> @pmaier for the Roadmap related items

**Comment by micbar** [comment]
@dragotin @pmaier1 @labkode 
We need two more roles where "ListGrants" is set to false

# CERNBOX SpaceViewer

```go
func NewCBOxSpaceViewerRole() *Role {
	return &Role{
		Name: RoleCBOxSpaceViewer,
		cS3ResourcePermissions: &provider.ResourcePermissions{
			GetPath:              true,
			GetQuota:             true,
			InitiateFileDownload: true,
			ListContainer:        true,
			ListFileVersions:     true,
			ListGrants:           false,
			ListRecycle:          true,
			Stat:                 true,
		},
		ocsPermissions: PermissionRead,
	}
}
```

# CERNBOX SpaceEditor

```go
func NewCBoxSpaceEditorRole() *Role {
	return &Role{
		Name: RoleCBoxSpaceEditor,
		cS3ResourcePermissions: &provider.ResourcePermissions{
			CreateContainer:      true,
			Delete:               true,
			GetPath:              true,
			GetQuota:             true,
			InitiateFileDownload: true,
			InitiateFileUpload:   true,
			ListContainer:        true,
			ListFileVersions:     true,
			ListGrants:           false,
			ListRecycle:          true,
			Move:                 true,
			PurgeRecycle:         true,
			RestoreFileVersion:   true,
			RestoreRecycleItem:   true,
			Stat:                 true,
		},
		ocsPermissions: PermissionRead | PermissionCreate | PermissionWrite | PermissionDelete,
	}
}
```

**Comment by pmaier1** [comment]
> @pmaier please look into that and let us know what your opinion is.

Agree with @micbar. Best case these roles would be somehow customizable. For the general product, I'd like to have `ListGrants`  set to `true`. Anyway, I agree to first satisfy CERN desired behavior.

**Comment by micbar** [comment]
Further Clarification after some Research:

> Managers look like our admins. If a manager has "Can change space quota" change it for multiple spaces or only to the one that the user is a manager?

I was wrong about that. It is implemented like you need it. "only the space administrators (managers) can share or change permissions"

> Managers look like our admins. If a manager has "Can change space quota" change it for multiple spaces or only to the one that the user is a manager?

This permission is attached to the global User Role "Admin", so a User with that Role can change the quota on all spaces.

> OC10 has this concept that is named Guest Accounts. When do you plan to introduce it?

According to PM. this feature is on the after GA Roadmap.

My personal POV on this is still, that this could work on the edge branch. How can i test it?

**Comment by micbar** [comment]
@labkode ^

**Comment by labkode** [comment]
> Further Clarification after some Research:
> 
> > Managers look like our admins. If a manager has "Can change space quota" change it for multiple spaces or only to the one that the user is a manager?
> 
> I was wrong about that. It is implemented like you need it. "only the space administrators (managers) can share or change permissions"

Good!
> 
> > Managers look like our admins. If a manager has "Can change space quota" change it for multiple spaces or only to the one that the user is a manager?
> 
> This permission is attached to the global User Role "Admin", so a User with that Role can change the quota on all spaces.
> 

Good as well!
> > OC10 has this concept that is named Guest Accounts. When do you plan to introduce it?
> 
> According to PM. this feature is on the after GA Roadmap.
> 
> My personal POV on this is still, that this could work on the edge branch. How can i test it?

You can have a driver for OCIS based on the CERNBox one:
https://github.com/cs3org/reva/blob/master/pkg/cbox/user/rest/rest.go

The CS3APIS define a type of user named `LIGHWEIGHT` that does not have any personal quota assigned.
The Web UI in our fork understands this user type.

**Comment by labkode** [comment]
A priori, this issue can be closed. The only remaining item is the access for lightweight accounts to Spaces.
