### ISSUE TITLE
CERN: Integration with applications

### ISSUE THREAD

**Issue by labkode** [cs3org/reva#2968]
Includes support for WOPI related applications: Office 365
• With support for locking semantics across different applications
Non-WOPI related applications: pdf, image gallery, drawio, ...

**Comment by labkode** [comment]
This should be already in edge.
Locking is already implemented for the EOS driver.

**Comment by kulmann** [comment]
pdf-viewer and drawio exist as frontend-only apps in web. Image gallery is not implemented, yet.

**Comment by labkode** [comment]
@kulmann when I mean image gallery, I mean the image viewer, that is working on master, just to clarify

**Comment by kulmann** [comment]
> @kulmann when I mean image gallery, I mean the image viewer, that is working on master, just to clarify.
> 
> This: ![Screenshot 2022-07-01 at 09 12 22](https://user-images.githubusercontent.com/5175912/176843626-91655a8f-fe7b-4fd8-9973-246f09edbd77.png)

Thanks for clarifying! I thought you referred to the grid view, which is planned but not implemented.

Regarding locking, we also plan to show an indicator in the file list for locked files FYI.

**Comment by kulmann** [comment]
> So the file preview is working with edge?

Yes, the preview app and all thumbnails are working fine with edge.

**Comment by labkode** [comment]
Applications are there, the only missing part is that they need to honour the global urls:
#2965

**Comment by labkode** [comment]
Missing for applications to use global-urls, as per #2965

**Comment by kulmann** [comment]
As far as I can tell this has been implemented in https://github.com/owncloud/web/pull/7430
