### ISSUE TITLE
CERN: Single file sharing

### ISSUE THREAD

**Issue by labkode** [cs3org/reva#2969]
Allow single files to be shared with individuals and groups

**Comment by labkode** [comment]
@kulmann I think Web is good in this aspect. I confirm you in a few hours.

**Comment by labkode** [comment]
@kulmann yeah all good for Web, @diocas confirmed that this capability was pushed long ago to web.

**Comment by kulmann** [comment]
we adopted your contribution for the product as well. Working with web master + ocis with reva edge.

**Comment by labkode** [comment]
Closing, this one can be demoed.
