### ISSUE TITLE
Secure webdav interface for use in ScienceMesh

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/reva#3720]
From https://github.com/cs3org/OCM-API/issues/63#issuecomment-1462316428

> the WebDAV endpoint is open and the sharedSecret is always empty

Ah, that affects all servers that join Network Beta then, so something to fix before we continue working on 
Thanks for bringing this up @gmgigi96 - I wasn't aware of this and that affects all ScienceMesh sites that update to latest reva master in order to join Network Beta then, so something to fix before we continue working on https://github.com/pondersource/sciencemesh-php/issues/164

I have shut down mesh.pondersource.com now, and AFAIK nobody else is running this on an internet-facing server.

Next time any of us becomes aware of an issue like this please follow the [Coordinated Vulnerability Disclosure](https://en.wikipedia.org/wiki/Coordinated_vulnerability_disclosure) procedure of the ScienceMesh consortium.

It is out in the open now, and the damage was contained, but let's consider this one a practice round! :)

**Comment by glpatcern** [comment]
Just to clarify and put things in context: the endpoint is "open" in the sense that if one knows the token identifying the OCM share, that's all is needed to access the resource. In a way, it's as open as a public link.

While it is a welcome feature to support a secret, I don't think this is mandatory (and once again, it was never part of the OCM specs!).

**Comment by michielbdejong** [comment]
Ah OK! So instead of:
```
"protocols": {
  "webdav": {
    "sharedSecret": "secret",
    "permissions": [],
    "uri": "https://open-cloud-mesh.org/remote.php/webdav/path/to/resource"
  },
},
```
you basically send:
```
"protocols": {
  "webdav": {
    "sharedSecret": "",
    "permissions": [],
    "uri": "https://open-cloud-mesh.org/remote.php/webdav/**secret**/path/to/resource"
  },
},
```

**Comment by michielbdejong** [comment]
OK, so then it's actually not insecure. Sorry for the confusion!
