### ISSUE TITLE
grpc: use hashicorp go-plugin system over gRPC

### ISSUE THREAD

**Issue by butonic** [cs3org/reva#38]
https://github.com/hashicorp/go-plugin uses grpc to tie several "plugins" together. AFAICT we do a similar thing with reva. We should have a look if we can integrate it with reva. See https://packer.io/ as an example.

**Comment by butonic** [comment]
Hm, it is only recommended for localhost ... 
but if we want to develop custom extensions to reva we always have to patch the loader.go file and check out our code to a subdir of the reva source ...

**Comment by labkode** [comment]
@butonic Cool. I didn't know about that system. For the time being we can continue with what we have and later try to integrate it.

**Comment by labkode** [comment]
Closing this as ocis does something similar
