### ISSUE TITLE
Invite link should have host, not full URL as providerDomain

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/reva#3884]
The &providerDomain=https://example.com/ string is incorrect.

E.g. in order to accept https://sciencemesh.cesnet.cz/iop/meshdir/?token=edbb5656-98b6-49c0-9d7e-003ba17e873d&providerDomain=https://mesh.pondersource.com/ I need to manually edit the URL to https://sciencemesh.cesnet.cz/iop/meshdir/?token=edbb5656-98b6-49c0-9d7e-003ba17e873d&providerDomain=mesh.pondersource.com

Our code in the ScienceMesh apps for NC and OC-10 is https://github.com/pondersource/nc-sciencemesh/blob/oc-10-take-2/lib/Controller/AppController.php#L128

We're getting invite_link from https://github.com/cs3org/reva/blob/cd44ba4c83bd416b660bc66da1e46946a324d1e1/internal/http/services/sciencemesh/token.go#L134 so it's a Reva problem apparently

**Comment by glpatcern** [comment]
As being discussed in gitter, can you set the provider_domain in your configuration as in https://github.com/cs3org/reva/blob/master/examples/ocmd/server-1/ocmd-server-1.toml#L57-L59

**Comment by glpatcern** [comment]
We think we understand what's missing, there's another bit of config to add - yes, configuring Reva is hard... - to override that behavior:

```
[http.services.sciencemesh]
invite_link_template = "{{.MeshDirectoryURL}}?token={{.Token}}&providerDomain=your.reva.domain"
```

**Comment by michielbdejong** [comment]
@MahdiBaghbani can you try that out? If it works then we should add that to the .toml files in our dev-stock image and to the sciencemesh.toml template at https://github.com/cs3org/ocm-test-suite/blob/main/servers/revad/sciencemesh.toml

**Comment by MahdiBaghbani** [comment]
I can confirm this problem is resolved and the `providerDomain` doesn't include https:// anymore.

**Comment by glpatcern** [comment]
Very good! I think we'll make the configuration easier here, but at least the issue can be closed.
