### ISSUE TITLE
problems with Nextcloud + reva integration. Shares are not visible in reva

### ISSUE THREAD

**Issue by marqsbla** [cs3org/reva#3979]
We've been testing jupyter plugin CS3API4LAB developed in CS3MESH4EOSC project to work with combination of nextcloud (26.0.1) + scienmesh app (0.4.0 from app store) + reva (1.24). 

Nextcloud + reva works fine. It allows to share the files between users at different sites, to both nextcloud and owncloud. 
Unfortunately the problem we are facing is that these shares are not visible within reva. They are stored in nextcloud's database (postgres). 

Reva allows jupyter to see all the contacts, and local nextcloud files, but not the files shared via nextcloud. 

The question is, is it an expected behavior? We also checked using reva cli, connected to revad service, that the share list is empty.

I attach also my reva config file:
[revad-no-secrets.toml.txt](https://github.com/cs3org/reva/files/11757184/revad-no-secrets.toml.txt)

**Comment by michielbdejong** [comment]
> these shares are not visible within reva. They are stored in nextcloud's database (postgres).

In this case 'visible' means whether or not they show up in `ocm-share-list` and `ocm-share-list-received`, right?
This is *not* expected behaviour and it's surprising that you were able to create shares but then don't see them in the list.
Can you try what happens if you do `ocm-share-create` from reva-cli? Does a share get added in the `oc_share` db table on the sending side and in the `oc_share_external` table on the receiving side? And does it show up in  `ocm-share-list` and `ocm-share-list-received` respectively? If not, then we should probably create a separate issue about that and debug your setup.

> Reva allows jupyter to see [...] local nextcloud files, but not the files shared via nextcloud.

This may seem equivalent but it is an entirely different question from our point of view :)
It would depend on whether or not the shares show up in `ls /home` on the receiving side or not, which as far as I know is not implemented. I don't think there is a way to browse incoming shares through reva on the receiving side. At a minimum, you should update to the latest config where you run 3 revad processes from 3 toml files (see latest 'join sciencemesh' docs).

**Comment by glpatcern** [comment]
It is possible to browse incoming shares, and this is how we make CERNBox  <--> CERNBox federated sharing work. Indeed that requires the 3 revad processes setup. In our case we use a sql driver to persist (and retrieve) the federated shares, not sure what is the state with the json driver. I'll check that.

**Comment by michielbdejong** [comment]
@marqsbla can you update your site to the latest instructions and try again?
This should probably be fixed when you do that, closing this issue for now.

**Comment by marqsbla** [comment]
ok, I will give a try today. Thanks a lot for help.

**Comment by marqsbla** [comment]
Just checking (sorry, but failed to do it sonner), before updating to 3 reva processes. 

I can see the files while ls: 
```
 ls /home/
ama-dablam2-most-beautiful-mountains-in-the-world.webp
FolderWithTextFile
MarekToCesnet
MarekToPondersourceCom
MarekToPondersourceOrg
mountains-7ddde89.jpg
up2digi.svg
Lake-Constance.jpg
ShareWithThirsa
analysis-of-data-from-psnc
vorteile.png
ls /home/analysis-of-data-from-psnc
analysis.md
```
where analysis-of-data-from-psnc is shared with me by 33c5b2a6e2feb8d4b5f639cd9c2ca76680fdb0b5@oc-mesh.du.cesnet.cz

whereas:
```
>> ocm-share-list-received
+---+-----------+----------------+---------------+------+-------------+------------------+---------+---------+-------+-----------+
| # | OWNER.IDP | OWNER.OPAQUEID | REMOTESHAREID | TYPE | GRANTEE.IDP | GRANTEE.OPAQUEID | CREATED | UPDATED | STATE | SHARETYPE |
+---+-----------+----------------+---------------+------+-------------+------------------+---------+---------+-------+-----------+
+---+-----------+----------------+---------------+------+-------------+------------------+---------+---------+-------+-----------+
>> ocm-share-list
+----+-----------+----------------+------------+----------------------+--------------------+-------------+------------------+-------------------------------+-------------------------------+
| #  | OWNER.IDP | OWNER.OPAQUEID | RESOURCEID | TYPE                 | SHARETYPE          | GRANTEE.IDP | GRANTEE.OPAQUEID | CREATED                       | UPDATED                       |
+----+-----------+----------------+------------+----------------------+--------------------+-------------+------------------+-------------------------------+-------------------------------+
| 24 |           |                | <nil>      | GRANTEE_TYPE_INVALID | SHARE_TYPE_INVALID |             |                  | 1970-01-01 01:00:00 +0100 CET | 1970-01-01 01:00:00 +0100 CET |
| 30 |           |                | <nil>      | GRANTEE_TYPE_INVALID | SHARE_TYPE_INVALID |             |                  | 1970-01-01 01:00:00 +0100 CET | 1970-01-01 01:00:00 +0100 CET |
| 33 |           |                | <nil>      | GRANTEE_TYPE_INVALID | SHARE_TYPE_INVALID |             |                  | 1970-01-01 01:00:00 +0100 CET | 1970-01-01 01:00:00 +0100 CET |
+----+-----------+----------------+------------+----------------------+--------------------+-------------+------------------+-------------------------------+-------------------------------+
```
So the files are there, but shares no. 

I can create new shares with ocm_share_create, and they are visible within reva, not in nextcloud, nor its db. 

I will try the setup with 3 revas.
