### ISSUE TITLE
grpc: add uuid_manager to authsvc

### ISSUE THREAD

**Issue by butonic** [cs3org/reva#40]
Some storage providers and other services need a non-reassignable globally unique identifier for a user. 

I propose to add make adding uuids to the user optional, by
- [ ] adding a uuid_manager to the authsvc 
- [ ] adding a `uuid` attribute to the user.User struct

See also https://github.com/owncloud/nexus/issues/2#issuecomment-470474162 for the thought process behind this.

**Comment by butonic** [comment]
we have the [UserID](https://cs3org.github.io/cs3apis/#cs3.types.UserId) which contains an `Idp` and an `OpaqueId`. The OpaqueId is described as `the unique identifier for the user in the scope of the identity provider.`
@labkode Can we add non-reassignable? The username is in the [User](https://cs3org.github.io/cs3apis/#cs3.authv0alpha.User) struct

If so, we can close this.

**Comment by madsi1m** [comment]
>Can we add non-reassignable?
I think we can

**Comment by labkode** [comment]
We can

**Comment by labkode** [comment]
https://github.com/cs3org/cs3apis/issues/50
