### ISSUE TITLE
Add CERNBox to docker-based tests

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/reva#4132]
We should add a CERNBox configuration to https://github.com/cs3org/reva/tree/updated-sciencemesh-testing/examples/sciencemesh so we can test not only OC to OC, OC to NC, NC to NC and NC to OC, but also OC to CERNBox, CERNBox to OC, NC to CERNBox and CERNBox to NC.

@glpatcern do you think you can provide a config file that makes this possible?

**Comment by gmgigi96** [comment]
Yes we can provide it!

**Comment by glpatcern** [comment]
A bit more complex than initially thought: the idea is to be able to serve the (OCIS) UI from Reva, but that requires:
- completing https://github.com/cs3org/reva/pull/4246
- resurrecting https://github.com/cs3org/reva/pull/4062
- implementing a "reva plugin" for the UI

**Comment by labkode** [comment]
> * implementing a "reva plugin" for the UI
This one is WIP

**Comment by glpatcern** [comment]
This was eventually done with nginx, which mimics exactly what we run in production, as the "reva plugin" for the UI was not continued. Also the docker scripts were moved to https://github.com/sciencemesh/dev-stock.
