### ISSUE TITLE
propfind / getsharebytoken issue

### ISSUE THREAD

**Issue by michielbdejong** [cs3org/reva#4142]
As mentioned by @glpatcern in today's FDTF hackathon

* basic ORRO scenario through https://github.com/cs3org/reva/tree/updated-sciencemesh-testing/examples/sciencemesh#sciencemesh-development-setup
* updated-sciencemesh-testing branch of reva
* https://github.com/mahdiBaghbani/nc-sciencemesh/tree/owncloud fork of sciencemesh app
* create a share
* using the share id, do a propfind, for instance:
```
curl -X PROPFIND https://revaowncloud1.docker/remote.php/dav/ocm/bbF3UTU...5yO/file.txt
```

**Comment by glpatcern** [comment]
This seems related to https://github.com/sciencemesh/nc-sciencemesh/issues/45 - share permissions are now properly taken into account by the PHP SM app (code is still to be merged but tests are OK)
