### ISSUE TITLE
ListFolder Permissions

### ISSUE THREAD

**Issue by MahdiBaghbani** [cs3org/reva#4157]
https://github.com/cs3org/reva/blob/e2ffbc22dea542de73738615591f5fab8af9d510/pkg/storage/fs/nextcloud/nextcloud.go#L436-L439

since `PermissionSet` no longer exists on the returned json from SM app, it only returns permissions now and permissions is integer and should be converted, is `ListFolder` doing its job correctly? since the structure in Go pointer mapping function expects `PermissionSet`.
Some tests fails because the mapping apparently doesn't happen.

**Comment by MahdiBaghbani** [comment]
Fixed via https://github.com/cs3org/reva/pull/4115/commits/1847b8baf8a009c27dfa2b94cf92307a86d0375c

This is also the reason of https://github.com/sciencemesh/nc-sciencemesh/issues/46

**Comment by michielbdejong** [comment]
Good observation, great work @MahdiBaghbani!
