### ISSUE TITLE
Remove auth token managers support

### ISSUE THREAD

**Issue by labkode** [cs3org/reva#420]
@refs @butonic I wonder if we could remove the configuration flexibility for the token_managers to only use JWT, that would allow us to have a security section in the config where we define the secret rather than having to repeat in different authentication logic:

```
[security]
secret = "Pive-Fumkiu4"
```

rather than 
```
[http.middlewares.auth.token_managers.jwt]
secret = "Pive-Fumkiu4"
```

**Comment by madsi1m** [comment]
That would make the configs slightly easier to follow

**Comment by butonic** [comment]
Yes, makes sense. I reduced the token manager jwt secret section to a single env var for ocis. Go for it!

**Comment by labkode** [comment]
Closing, the section is now called [shared]
