### ISSUE TITLE
update github.com/golang-jwt/jwt to v5

### ISSUE THREAD

**Issue by butonic** [cs3org/reva#4952]
https://github.com/golang-jwt/jwt has a [migration guide](https://github.com/golang-jwt/jwt/blob/main/MIGRATION_GUIDE.md) how to update to v5.

It brings a Leeway Option that helps to deal with clock skew errors:
```go
var v = jwt.NewValidator(jwt.WithLeeway(5*time.Second))
v.Validate(myClaims)
```

**Comment by rhafer** [comment]
Fix was merged
