### ISSUE TITLE
make deps fails: cd: can't cd to golangci-lint/cmd/golangci-lint

### ISSUE THREAD

**Issue by ishank011** [cs3org/reva#531]
Make [uses sh](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html#tag_20_76_13_03) by default to execute scripts, which does not recognize the [&>](https://github.com/cs3org/reva/blob/master/Makefile#L47) operator. It thus interprets the ampersand as an indication to run the command in the background, causing the succeeding `cd` command to execute without the clone operation being completed, causing it to fail.

**Comment by labkode** [comment]
@ishank011 #533 should fix that problem, I've added you as maintainer (you need to accept) so you can test it and then approve the PR.
