### ISSUE TITLE
Allow sharing of single files

### ISSUE THREAD

**Issue by madsi1m** [cs3org/reva#632]
It seems I can share folders but not individual files. This is an important use case for us as our uses do this to work on the same office doc/excell file.

It seems when trying to share a file reva creates a folder in .shadow of the file eg `.shadow/user/MyShares/test.txt/` and the attr on the file might be missing `sys.acl`

See @labkode for more detail on the technical side

**Comment by butonic** [comment]
AFAIK eos cannot set ACLs on individual files. files always derive their ACLs from the directory. From: https://github.com/cern-eos/eos/blob/master/doc/configuration/permission.rst
> 2. Permissions are only checked in the direct parent, EOS is not walking through the complete directory hierarchy.
@labkode please correct me if I am wrong or if you have an idea how to work around this.

**Comment by labkode** [comment]
@butonic I'm checking with the EOS devs.

**Comment by labkode** [comment]
@butonic what we do in CERNBox is that we point to the version folder, is a hack but it works, we can do that already. Also, if you add the ACL to the file, once you update the file the file will get a new ID so the share will point to a previous version which is not user friendly. Let my add that.

**Comment by labkode** [comment]
@butonic @madsi1m according to Andreas from EOS development, a recent feature was added to support ACLs on files, (RichACL support I think is called), documentation will be updated and we'll see how we enable sharing of files with persistence on the storage. This "new" feature is something we have never use in CERNBOX+EOS deployment.

**Comment by madsi1m** [comment]
What EOS version did this feature come in? Might as well update my dev setup

**Comment by butonic** [comment]
slowly preparing reva with https://github.com/cs3org/reva/pull/1170
