### ISSUE TITLE
Improve configuration

### ISSUE THREAD

**Issue by butonic** [cs3org/reva#65]
I had a lengthy discussion with @felixboehm  about the toml config file ... while I like the declarative nature of it Felix would like to see some form of dynamic configuration, so an admin can do
```
wget https://.../reva
reva
reva service enable ocdavsvc
reva service enable authsvc
reva service enable storageprovider --driver local
```
to get a working instance.

To me that is sugar on top. AFAICT the cli still needs to change the config and kick the reva process to reload the changes (or we add monitoring, but the less magic the better IMO). @labkode IIRC you mentioned reva or the os being able to queue any requests while reva is restarting / rereading the config. Could you elaborate and give an example? Maybe as a PR in the docs?

Anyway, I do agree that the single config file mixes two things that should be separate:
1. the services that should be started
2. the configuration for each service

I think we should use a config folder that contains a config file per service. Each service should write its default config if it is not present. That way the services are responsible for defining their configuration.
Reva itself should maybe write individual config files for core.toml, log.toml http.toml and grpc.toml
Maybe the services should have a subfolder in the reva config dir. That would allow them to freely choose config file names, without being able to overwrite another services config.

When using docker containers we can then mount a config dir (passing in env vars should still be possible in order to overwrite individual settings)

**Comment by labkode** [comment]
@butonic @felixboehm the configuration of REVA focuses on simplicity, like NGINX does, I took inspiration from it. As Jorn mentioned *reva service enable authsvc* is just sugar to avoid having to do:

```
vim /etc/revad/revad.toml
systemctl restart revad
```

Changes to REVA need to be driven by the configuration file, what you put in the config is what you get when you run the service. The oc model of having the DB to store important configuration items is not sysadmin-friendly at all and complicates debugging. 

I think we need to strive for simplicity, it's very easy to explain that if you want X you put X in the config file. Having multiple config files like NGINX/Apache do can be considered.

NGINX provides well documented defaults when you don't set any configuration for a module, the same should apply to REVA, hence no need to have default configuration files per service.

**Comment by labkode** [comment]
For reloading the configuration:

```
./cmd/revad/revad -p revad.pid -s reload
``` 
is a TODO :)

You can just kill -s SIGHUP pid

If you are in a Docker container it will not work as the new process will be 2, and 1 will be killed which will kill the container.

**Comment by butonic** [comment]
ok, what are the defaults we should pick for reva and its services? by default it does not run anything. I wanted to document how to implement a storage provider and ended up explaining the config file in https://central.owncloud.org/t/digging-into-the-reva-hello-world-example-md/19896 ... only to stumble upon https://github.com/cernbox/reva/blob/master/docs/beginner-guide.md which basically does the same thing.

If we want reva a generic framework it should only render the hello world thing. However, I think it makes more sense to have it start a sensible set of services because it is inteded to be the referece implmentation of the CS3 apis. As such it should:
- start ocdasvc so you can interface with existing clients via webdav
- a local storage provider
  - with a data dir relative to the location of the executable
  - with inotify for file changes (to be implemented)
- an authsvc
  - with basic auth, because oidc requires many more services
  - with the example users ... or with a yet to implement user backend that allows adding users with the `reva` cli
- config file(s) should be created on first run

that is kind of the minimal config I see. @labkode @felixboehm opinions?

**Comment by labkode** [comment]
@butonic I agree that those basic services should be the default services so you can play with REVA out of the box.

We need to come up with a basic config file to use like prometheus tells you to do so in:
https://prometheus.io/docs/prometheus/latest/getting_started/#getting-started

The bootstrap services needs to be configured in the config file while the configuration for those can use defaults. If we lunch reva without a config file, it will assume that runs those services by defaults and you will need a negative config directive to disable default services ... and that is ugly.

**Comment by butonic** [comment]
@tboerger could you give us your strongest opinion on this?

**Comment by refs** [comment]
FWIW, I tried creating a config file from scratch that uses the reva command. It is the bare minimum one would need to start a reva service and start messing around with it. It attempts to explain each directive used. It is the cleanest solution I've come across. The creation of this file involved digging a bit into the reva setup (loaders) and the `type config ...` of each service. [The file can be found here](https://gist.github.com/refs/2ec0d52d3bafbb121de8c7720bc62d74), so this thread is not bloated. /cc @labkode @butonic @IljaN

**Comment by butonic** [comment]
we added an opinrionated config in ocis and reva has reduced some config overhead as well! :rocket:
