### ISSUE TITLE
Change runtime api to be able to pass zerolog instance?

### ISSUE THREAD

**Issue by IljaN** [cs3org/reva#659]
It would be nice if there was an option to pass a fully pre-configured zerolog instance to the reva-runtime to have the same logging-style everywhere.

https://github.com/cs3org/reva/blob/0dbce24f7e8b508c1ecab2d145979562888a7a76/cmd/revad/runtime/runtime.go#L47

Any ideas on how the redesigned runtime api should look like?

**Comment by labkode** [comment]
Hi @IljaN, can you prototype another function: 

```RunWithOptions(mainConf map[string]interface{}, pidFile string, opts ...[]*Option)```

So we can add methods like:

```WithLogger(log *zerolog.Logger) *Option``` to the runtime.
