### ISSUE TITLE
Throw error when `Reference` is used incorrectly

### ISSUE THREAD

**Issue by LovisaLugnegard** [cs3org/reva#724]
The field `Reference` (https://cs3org.github.io/cs3apis/#cs3.storage.provider.v1beta1.Reference) can contain `path` or `id` and it should never contain both. In some cases only `path` is implemented, in others only `id` and in others both are. If `Reference` contains both fields, or a field which is not implemented we should throw an error.

**Comment by ishank011** [comment]
It would only contain one of those since it implements oneOf.
