### ISSUE TITLE
Add log verbosity CLI argument

### ISSUE THREAD

**Issue by SamuAlfageme** [cs3org/reva#763]
I was just now debugging some issue with @ishank011 where we are seeing this error in the logs:

```
7:27PM ERR go/src/github/cs3org/reva/cmd/revad/runtime/runtime.go:180 > 
    error starting the grpc server error="unable to register services: 
        rgrpc: grpc service ocmproviderauthorizer does not exist" pid=1
```

He suggested debugging it by checking which services have been registered by including some extra logs in:

https://github.com/cs3org/reva/blob/2b018b13c24dab305d92164cf0ad4da43807060c/pkg/rgrpc/rgrpc.go#L159

Something like: 

```go
s.log.Info().Msgf("isServiceEnabled Services: %+v", Services)
```

However, It would be nice to add a runtime flag (e.g. `-vvv`) to control the level of verbosity in the logs, specially in scenarios like running reva in a container, where re-compiling with new logs is not really an option.

**Comment by ishank011** [comment]
@SamuAlfageme looking at the revad cmd code, we already have a log config option available which makes use of zerolog's [leveled logging](https://github.com/rs/zerolog#leveled-logging) and can be set as done [here](https://reva.link/docs/config/log/#level). So essentially, we have six levels but we hardly use some of those. It will be a good idea to use the trace option to start logging such details.

So would this be fine or should we add it to the cmd options as well?

**Comment by SamuAlfageme** [comment]
@ishank011 I see. The verbosity is there. But from the operation standpoint I'd go for adding also the cmd flag (that should take precedence over config file, in case it's present). 

When running `revad` from the container, it's easier to append a cmd flag than it is to modify the pre-existing config. For instance, in Prometheus cli: 

```console
$ prometheus -h | grep log
      --log.level=info           Only log messages with the given severity or above. One of: [debug, info, warn, error]
      --log.format=logfmt        Output format of log messages. One of: [logfmt, json]
```

@labkode @butonic any opinions on this?

**Comment by ishank011** [comment]
@SamuAlfageme sounds good. I'll start with adding the flag to the cmd options, and we can merge it once @labkode and @butonic approve.
