### ISSUE TITLE
Make meshdirectory and mentix services use cs3apis

### ISSUE THREAD

**Issue by ishank011** [cs3org/reva#870]
Hi @mirekys, @Daniel-WWU-IT 

As mentioned yesterday in the weekly meeting, we need to make calls to the meshdirectory service pass through the GRPC layer. Even though we'd ultimately be making a call to a gocdb server, but for other local-database-reliant drivers, in the current implementation, we just assume that the db would be present on the same machine on which the HTTP service is hosted, which won't always be the case.

I've modified the OCM provider CS3APIs definition to include all the fields which gocdb provides [here](https://cs3org.github.io/cs3apis/#cs3%2focm%2fprovider%2fv1beta1%2fresources.proto), and modified the reva methods to use these new definitions, the PR for which is [here](https://github.com/cs3org/reva/pull/864).

So I think we can carry out the following steps:
- Since the meshdirectory package's manager interface only has the `GetMeshProviders` method, which is also implemented by the OCM Provider package, we can make calls to the ocmprovider GRPC service as done [here](https://github.com/cs3org/reva/blob/master/internal/http/services/ocmd/invites.go#L120) from the meshdirectory HTTP service and move the mentix driver from meshdirectory package to ocm/provider package. Right now, we just have two packages which perform the same tasks.
- Gocdb has multiple definitions of the service and site structures, so we should use the CS3API definitions mentioned above.

Please let me know your thoughts about these.
CC: @labkode

**Comment by mirekys** [comment]
Thanks @ishank011, I completely agree that we should reuse what is already in OCM Provider and move Mentix driver from meshdirectory there. It is a good idea to have one common provider site structure both for GOCDB and meshdirectory. I can prepare a pull request for the mesh directory's part.

**Comment by ishank011** [comment]
Sounds good @mirekys. Thanks!
