### ISSUE TITLE
Implement a strict changelog requirement for every code change

### ISSUE THREAD

**Issue by micbar** [cs3org/reva#885]
## Description

To make reva usable for projects and the opensource community, having a transparent and comprehensible changelog.

## Proposal
- Reva already uses calens as a tool for automated changelog tracking and generation
- Implement a strict policy to add a changelog to every pr that touches the business logic

## Details
- At ownCloud, we are also using the calens tool since some time now. It works very well for us.
- Good example https://github.com/owncloud/ocis-proxy/tree/master/changelog

We don't enforce creating a changelog with a strict check, but we are using a github extension as a kind of "reminding bot"
![Screenshot_2020-06-25 add staticcheck to makefile by butonic · Pull Request #50 · owncloud ocis-proxy](https://user-images.githubusercontent.com/4378513/85738251-2bbe5b80-b700-11ea-914d-adacfe32fb3d.png)

We have an automated CI setup which adds the single version changes automatically to the respective github releases.
https://github.com/owncloud/ocis-proxy/blob/master/.drone.star#L348-L381

The main CHANGELOG.md is also automatically generated.

@labkode

**Comment by labkode** [comment]
@labkode changelog is automatically generated and is even pushed to the main documentation: https://reva.link/docs/changelog/0.1.0/

The missing item here is to remind people (even enforce) that contributors write the changelog.

For example, what about adding PR templates for contributing, like Restic does it:
https://github.com/restic/restic/blob/a307797c110b89697e0379528e7f4adf5f41f91f/.github/PULL_REQUEST_TEMPLATE.md

**Comment by micbar** [comment]
> For example, what about adding PR templates for contributing, like Restic does it:
Good idea.
We have that in our legacy server repo too.

**Comment by ishank011** [comment]
We have the changelog CI check now.
