### ISSUE TITLE
CI  failing with no space left on device

### ISSUE THREAD

**Issue by phil-davis** [cs3org/reva#942]
for example https://cloud.drone.io/cs3org/reva/1726/4/4
```
# google.golang.org/protobuf/internal/impl
compile: writing output: write $WORK/b164/_pkg_.a: no space left on device
# github.com/aws/aws-sdk-go/aws/endpoints
compile: writing output: write $WORK/b522/_pkg_.a: no space left on device
# github.com/mattn/go-sqlite3
sqlite3-binding.c:228449:1: fatal error: error writing to /tmp/ccF82QmE.s: No space left on device
 SQLITE_API const char *sqlite3_sourceid(void){ return SQLITE_SOURCE_ID; }
 ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:54: build-ci] Error 2
```

And there are plenty of examples of this today.

Did something change in cloud.drone.io ? Or is there some reva storage somewhere that is now full?

**Comment by labkode** [comment]
@phil-davis https://discourse.drone.io/t/no-space-left-on-cloud-drone-io/7650

**Comment by labkode** [comment]
@phil-davis it fails even on build time, would be possible that the API tests are creating files left and right? Could you test that by removing the parallell API tests?

**Comment by phil-davis** [comment]
From ashwilliams1 https://github.com/cs3org/reva/issues/942
"This issue has been resolved."
But no clue given about what was the root cause.
