### ISSUE TITLE
eosfs: don't rely on systemcall to obtain user unix IDs/GroupIds

### ISSUE THREAD

**Issue by labkode** [cs3org/reva#964]
In the EOS filesystem implementation we rely on using systemcalls to obtain the user uid/gid. This implies having local users where reva runs  and that sucks:
https://github.com/cs3org/reva/blob/master/pkg/storage/utils/eosfs/eosfs.go#L1219

We should obtain this information directly by calling the UserProviderAPI (through the Gateway).

**Comment by butonic** [comment]
we could mint the uid and gid into the token

**Comment by labkode** [comment]
@butonic that is a nice idea. The uid/gid are quite specific for the EOS filesystem so I think they should still be part of the Opaque part unless there are other fs that will needed and then we can make it first class citizen. Any thoughts?
